### ISSUE TITLE
Invalid key for Fernet

### ISSUE THREAD

**Issue by joshuakoh1** [leocavalcante/encrypt#167]
Hi guys,

Trying to can't seem to pass a base64 formatted string as Fernet key.

```
final f = encrypt.Fernet(encrypt.Key.fromBase64('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ='));
final e = encrypt.Encrypter(f);
```

```
E/flutter ( 9645): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 1)
E/flutter ( 9645): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783)
E/flutter ( 9645): #1      Utf8Decoder.convert (dart:convert/utf.dart:321)
E/flutter ( 9645): #2      Utf8Codec.decode (dart:convert/utf.dart:62)
E/flutter ( 9645): #3      new Fernet (package:encrypt/src/algorithms/fernet.dart:12)
```

**Comment by leocavalcante** [comment]
Hi @timfeirg 
Can you help us on why there is a utf-8 decoding of the key at https://github.com/leocavalcante/encrypt/blob/master/lib/src/algorithms/fernet.dart#L12

**Comment by timfeirg** [comment]
this question has been answered in the time of its relevant pull-request: https://github.com/leocavalcante/encrypt/pull/66#discussion_r313688914

**Comment by joshuakoh1** [comment]
@timfeirg The multiple conversions might be confusing me but when I try to create a Key with 32 byte Uint8List I'm still getting the same error.
https://github.com/leocavalcante/encrypt/blob/master/lib/src/encrypted.dart#L65
```
final f = encrypt.Fernet(encrypt.Key(base64Url.decode('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ=')));
```
```
E/flutter (17446): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 1)
E/flutter (17446): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783)
E/flutter (17446): #1      Utf8Decoder.convert (dart:convert/utf.dart:321)
E/flutter (17446): #2      Utf8Codec.decode (dart:convert/utf.dart:62)
E/flutter (17446): #3      new Fernet (package:encrypt/src/algorithms/fernet.dart:12)
```
I'm not very good with conversion between types but it seems that while base64Url.decode returns a valid bytes list, it does not utf8 decode. 
```
print(base64Url.decode('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ='))
>>> [32, 23, 235, 27, 227, 15, 113, 81, 39, 43, 213, 165, 230, 163, 1, 202, 105, 132, 56, 26, 12, 152, 49, 31, 6, 173, 138, 220, 121, 178, 69, 196]
print(utf8.decode([32, 23, 235, 27, 227, 15, 113, 81, 39, 43, 213, 165, 230, 163, 1, 202, 105, 132, 56, 26, 12, 152, 49, 31, 6, 173, 138, 220, 121, 178, 69, 196]))
>>> FormatException: Missing extension byte (at offset 1)
```
I'm not having issues encrypting/decrypting with python
```
fernet = Fernet('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ='.encode('utf-8'))
data = fernet.decrypt('Test Payload')
d = fernet.decrypt(data.encode('utf-8'))
```
I tried to encrypt it the same way as with python
```
final f = encrypt.Fernet(encrypt.Key(utf8.encode('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ=')));
```
Same issue
```
E/flutter (20170): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: Fernet key must be 32 url-safe base64-encoded bytes.
E/flutter (20170): #0      new Fernet (package:encrypt/src/algorithms/fernet.dart:15:7)
```

**Comment by timfeirg** [comment]
can you reproduce this error using the examples [from the readme](https://github.com/leocavalcante/encrypt#fernet)?

**Comment by joshuakoh1** [comment]
I can't because I need to pass a generated key from python instead of a utf8 string.

**Comment by joshuakoh1** [comment]
If I pass the b64 key as a UTF8 string like in the examples, I get an invalid token trying to decrypt it with the python function above. I believe you need a separate way to init the Fernet method directly with a b64 string without using a Key object.
```
  final b64key = encrypt.Key.fromUtf8(base64Url.encode('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ='));
  final f = encrypt.Fernet(b64key);
  final e = encrypt.Encrypter(f);
```
Python throws InvalidToken as expected since the keys are completely different.
```
  final b64key = encrypt.Key.fromUtf8(base64Url.encode(base64Url.decode('IBfrG-MPcVEnK9Wl5qMBymmEOBoMmDEfBq2K3HmyRcQ=')));
  final f = encrypt.Fernet(b64key);
  final e = encrypt.Encrypter(f);
```
```
E/flutter (28933): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Bad state: Fernet key must be 32 url-safe base64-encoded bytes.
E/flutter (28933): #0      new Fernet (package:encrypt/src/algorithms/fernet.dart:15:7)
```

**Comment by joshuakoh1** [comment]
I made a quick fix for my use case. 
If someone wants to refactor the code nicely for the next release it would probably be better @leocavalcante @timfeirg. Imo it makes no sense to only support encryption via key string.
Cheers.

```
  Fernet.fromBytes(Uint8List keyBytes, {Clock clock}) {
    if (keyBytes.length != 32) {
      throw StateError('Fernet key must be 32 url-safe base64-encoded bytes.');
    }
    _signKey = Key(Uint8List.fromList(keyBytes.sublist(0, 16)));
    _encryptionKey = Key(Uint8List.fromList(keyBytes.sublist(16)));
    if (clock == null) {
      _clock = Clock();
    } else {
      _clock = clock;
    }
  }

  Fernet.fromB64UrlString(String b64, {Clock clock}) {
    Uint8List keyBytes = base64Url.decode(b64);
    this.fromBytes(keyBytes);
  }
```

**Comment by leocavalcante** [comment]
@joshuakoh1 
When possible, could you check if [v4.0.3](https://pub.dev/packages/encrypt/versions/4.0.3) solves it for you, please?
