### ISSUE TITLE
encrypt big file use stream success but dencrypt this file failed use aes.ctr mode 

### ISSUE THREAD

**Issue by inits** [leocavalcante/encrypt#232]
the error info below:

```
inits@iMac bin % dart run dtest1.dart

Unhandled exception:
Invalid argument(s): Input data length must be a multiple of cipher's block size
#0      PaddedBlockCipherImpl.process (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:60:9)
#1      AES.decrypt (package:encrypt/src/algorithms/aes.dart:63:22)
#2      Encrypter.decryptBytes (package:encrypt/src/encrypter.dart:25:17)
#3      Qencrypt.dencrypt (file:///Users/inits/Desktop/test/dtest1/bin/dtest1.dart:17:10)
#4      QFile.dfencrypt (file:///Users/inits/Desktop/test/dtest1/bin/dtest1.dart:51:36)
<asynchronous suspension>
```

the example code is below:

```
import 'dart:io';
import 'dart:typed_data';
import 'package:chunked_stream/chunked_stream.dart';
import 'package:encrypt/encrypt.dart';

extension Qencrypt on Uint8List {
  Uint8List qencrypt({required String keys}) {
    final key = Key.fromUtf8('xxeejjlleeiixxljxxeejjllee' + keys);
    return Encrypter(AES(key, mode: AESMode.ctr))
        .encryptBytes(this, iv: IV.fromUtf8('jjsskkxl'))
        .bytes;
  }

  Uint8List dencrypt({required String keys}) {
    final key = Key.fromUtf8('xxeejjlleeiixxljxxeejjllee' + keys);
    final decrypted = Encrypter(AES(key, mode: AESMode.ctr))
        .decryptBytes(Encrypted(this), iv: IV.fromUtf8('jjsskkxl'));
    return Uint8List.fromList(decrypted);
  }
}

// 用于加密大文件stream方式读取
extension QFile on File {
  Future<void> qfencrypt({required File outFile, required String key}) async {
    final reader = ChunkedStreamIterator(openRead());
    while (true) {
      var data = await reader.read(1023 * 50); // read one byte
      if (data.isEmpty) {
        // print('End of file reached');
        break;
      }
      // print('next byte: ${data[0]}');
      await outFile.writeAsBytes(
          Uint8List.fromList(data).qencrypt(
            keys: key,
          ),
          mode: FileMode.append);
    }
  }

  Future<void> dfencrypt({required File outdFile, required String key}) async {
    final reader = ChunkedStreamIterator(openRead());
    while (true) {
      var data = await reader.read(1023 * 50); // read one byte
      if (data.isEmpty) {
        // print('End of file reached');
        break;
      }
      // print('next byte: ${data[0]}');
      await outdFile.writeAsBytes(
          Uint8List.fromList(data).dencrypt(
            keys: key,
          ),
          mode: FileMode.append);
    }
  }
}

void main() {
  var inputfile = File('./unetbootin.dmg');

  var encrypt_outfile = File('./unetbootin-encrypt.dmg');

  var dencrypt_file = File('./unetbootin-dencrypt.dmg');

  // encrypt file
  // inputfile.qfencrypt(outFile: encrypt_outfile, key: 'abc123');

  // dencrypt file

  encrypt_outfile.dfencrypt(outdFile: dencrypt_file, key: 'abc123');
}

```

**Comment by josh4500** [comment]
I'm have same issue

**Comment by Napcrypto1** [comment]
Having the same issue

**Comment by Abdelazeem777** [comment]
Use `CTR` mode with `null` padding for both `Encryption` and `Decryption`
