### ISSUE TITLE
AES mode cbc can‘t process base64

### ISSUE THREAD

**Issue by zengzhengrong** [leocavalcante/encrypt#98]
## front-side by JS (CryptoJS)
```
const key = Crypto.enc.Base64.parse('my-key-cipher');
const iv = Crypto.enc.Base64.parse('my-iv-cipher');

const encrypted = CryptoJS.AES.encrypt(password,key,{iv:iv});
const c_text = encrypted.ciphertext.toString(CryptoJS.enc.Base64);
```
CryptoJS.AES default mode : cbc with Pkcs7

## mobile-side by flutter(encrypt)
```
void main() {
  final plainText = 'im a password';
  final key = Key.fromBase64('my-key-cipher');
  final iv = IV.fromBase64('my-iv-cipher');

  final encrypter = Encrypter(AES(key,mode: AESMode.cbc));
  final encrypted = encrypter.encrypt(plainText, iv: iv);
  print(encrypted.base64);
  final decrypted = encrypter.decrypt(encrypted, iv: iv);
  print(decrypted);
}
```
## Get Error 
```
Invalid argument(s): Initialization vector must be the same length as block size
#0      CBCBlockCipher.init (package:pointycastle/block/modes/cbc.dart:49:7)
#1      PaddedBlockCipherImpl.init (package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:43:12)
#2      AES.encrypt (package:encrypt/src/algorithms/aes.dart:19:9)
#3      Encrypter.encryptBytes (package:encrypt/src/encrypter.dart:12:19)
#4      Encrypter.encrypt (package:encrypt/src/encrypter.dart:20:12)
#5      main (file:///G:/workspace/flutter/dart-practice/main.dart:64:31)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
iv and key  both same length , I try to change ```fromBase64``` to ```fromBase16```,that is work fine 

but i server-side is base64!~

**Comment by leocavalcante** [comment]
Can you share how this base64 looks like?

**Comment by zengzhengrong** [comment]
> Can you share how this base64 looks like?

key:5b8e151628dea2a6abf7158809cf4f3c
iv:3ad77bb40d7a3660a89face32466ef79

**Comment by leocavalcante** [comment]
They are clearly hexdex, not base64.
